name: bitbucket-cli
summary: Bitbucket CLI
description: |
      The Bitbucket Command Line Interface brings the power of the Bitbucket
      platform to your command line. Creating and merging Pull Requests, cloning
      repositories, and more are now just a few keystrokes away.

      Note: This snapcraft is not affiliated with Atlassian.
website: https://github.com/gildas/bitbucket-cli
source-code: https://github.com/gildas/bitbucket-cli
issues: https://github.com/gildas/bitbucket-cli/issues
license: MIT
version: 0.16.0
base: core22
grade: stable
confinement: strict

plugs:
  dot-config-bb:
    interface: personal-files
    write:
      - $HOME/.config/bitbucket/config-cli.yml
      - $HOME/.bitbucket-cli

apps:
  bb:
    command: bin/bb
    plugs:
      - home
      - dot-config-bb
      - network

parts:
  bb:
    plugin:      go
    source-type: git
    source:      https://github.com/gildas/bitbucket-cli
    build-snaps: [go]
