name: bitbucket-cli
title: Bitbucket CLI
summary: Bitbucket CLI
description: |
      The Bitbucket Command Line Interface brings the power of the Bitbucket
      platform to your command line. Creating and merging Pull Requests, cloning
      repositories, and more are now just a few keystrokes away.

      Note: This snapcraft is not affiliated with Atlassian.
website: https://github.com/gildas/bitbucket-cli
source-code: https://github.com/gildas/bitbucket-cli
issues: https://github.com/gildas/bitbucket-cli/issues
contact:
  - https://github.com/gildas/bitbucket-cli
license: MIT
version: 0.17.4
base: core24
grade: stable
confinement: strict

platforms:
  amd64:
    build-on:  [amd64]
    build-for: [amd64]
  arm64:
    build-on:  [arm64]
    build-for: [arm64]

plugs:
  dot-config-bb:
    interface: personal-files
    write:
      - $HOME/.config/bitbucket/config-cli.yml
      - $HOME/.bitbucket-cli

apps:
  bb:
    command: bin/bb
    plugs:
      - home
      - dot-config-bb
      - network

parts:
  bb:
    plugin:      go
    source-type: git
    source:      https://github.com/gildas/bitbucket-cli
    build-snaps: [go/latest/stable]
